version: "3.7"

services:
  elasticsearch:
    container_name: "es-node"
    image: elasticsearch:8.3.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  redis:
    container_name: "redis"
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - elastic

  #ingestor:
  #  container_name: "music-collection-etl"
  #  build: 'Dockerfile'
  #  entrypoint: "dotnet ...."
  #  depends_on:
  #    - elasticsearch

networks:
    elastic:
      driver: bridge

volumes:
  elasticsearch-data:
    driver: local